tap "hashicorp/tap"
tap "stripe/stripe-cli"
tap "mongodb/brew"

brew "mas"
brew "stow"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "starship"
brew "zoxide"
brew "fzf"
brew "fd"
brew "lsd"
brew "bat"
brew "tldr"
brew "yazi"
brew "ffmpeg"
brew "p7zip"
brew "poppler"
brew "ripgrep"
brew "jq"
brew "tmux"
brew "lazygit"
brew "wget"
brew "nvim"
brew "asdf"
brew "gpg"
brew "gawk"
brew "yarn"
brew "pnpm"
brew "mkcert"
brew "hashicorp/tap/terraform"
brew "stripe/stripe-cli/stripe"
brew "mongodb/brew/mongodb-database-tools"
brew "awscli"
brew "mongodb-community"

cask "1password"
cask "1password-cli"
cask "raycast"
cask "ghostty"
cask "dockey"
cask "docker-desktop"
cask "istherenet"
cask "cleanshot"
cask "shottr"
cask "iina"
cask "figma"
cask "affinity-photo"
cask "affinity-designer"
cask "spotify"
cask "craft"
cask "zen"
cask "codex"
cask "bruno"
cask "zed"

cask "font-hack-nerd-font"
cask "font-outfit"
cask "font-inter"
cask "font-noto-sans"
cask "font-poppins"
cask "font-birthstone"

mas "Dropover - Easier Drag & Drop", id: 1355679052
mas "TripMode", id: 1513400665
mas "Pandan", id: 1569600264
mas "Menu Bar Calendar", id: 1558360383

