brew "mas"
brew "stow"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "starship"
brew "zoxide"
brew "fzf"
brew "fd"
brew "lsd"
brew "bat"
brew "tldr"
brew "yazi"
brew "ffmpeg"
brew "poppler"
brew "ripgrep"
brew "jq"
brew "tmux"
brew "lazygit"
brew "wget"
brew "nvim"
brew "asdf"
brew "gpg"
brew "gawk"
brew "pnpm"
brew "stripe-cli"
brew "mkcert"

cask "1password"
cask "1password-cli"
cask "raycast"
cask "font-hack-nerd-font"
cask "ghostty"
cask "dockey"
cask "docker"
cask "docker-desktop"
cask "jordanbaird-ice"
cask "istherenet"
cask "cleanshot"
cask "shottr"
cask "iina"
cask "figma"
cask "affinity-photo"
cask "affinity-designer"
cask "spotify"
cask "todoist-app"
cask "craft"
cask "vivaldi"

mas "Dropover - Easier Drag & Drop", id: 1355679052
mas "TripMode", id: 1513400665
mas "Pandan", id: 1569600264

